apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: renova-prueba
  name: renova-prueba
spec:
  replicas: 1
  selector:
    app: renova-prueba
    deploymentconfig: renova-prueba
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: renova-prueba
        deploymentconfig: renova-prueba
    spec:
      containers:
        - name: renova-prueba
          image: image-registry.openshift-image-registry.svc:5000/mi-movistar/renova-prueba:latest
          env:
            - name: SPRING_APPLICATION_JSON
              value: '{"server":{"undertow":{"io-threads":10, "worker-threads":80 }}}'
            - name: JAVA_OPTIONS
              value: '-Xms640m -Xmx1024m -Dfile.encoding=ISO-8859-1'
          readinessProbe:
            httpGet:
              path: /WebHook/health
              port: 8080
              scheme: HTTP
            failureThreshold: 3
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 120
          livenessProbe:
            httpGet:
              path: /WebHook/health
              port: 8080
              scheme: HTTP
            failureThreshold: 2
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 120
          resources:
            limits:
              cpu: 400m
              memory: 1024Mi
            requests:
              cpu: 100m
              memory: 300Mi