apiVersion: apps/v1
kind: Deployment
metadata:
  name: renova-prueba-deployment
  namespace: renova-prueba
  labels:
    event: renova-prueba
    name-space: renova-prueba
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      event: renova-prueba
  template:
    metadata:
      labels:
        event: renova-prueba
    spec:
      containers:
        - image: jcpuerta1/archetype:latest
          name: renova-prueba
          imagePullPolicy: IfNotPresent
          env:
          - name: JAVA_OPTS
            value: '-Xmx512m -Xmx1024m -XX:+UseG1GC'
          resources:
            limits:
              memory: 512Mi
              cpu: 200m
            requests:
              memory: 512Mi
              cpu: 200m
          ports:
            - containerPort: 8080         
      
---
apiVersion: v1
kind: Service
metadata:
  name: renova-prueba-service
  namespace: renova-prueba
  labels:
    event: renova-prueba
    name-space: renova-prueba
spec:
  type: NodePort
  ports:
    -
      port: 8080
      targetPort: 8080 
      nodePort: 32108
  selector:
    event: renova-prueba